FROM python:3.6

ENV PYTHONPATH "${PYTHONPATH}:."

RUN apt-get update\ 
  && apt-get install -qq -y\
 zip wget curl locales ca-certificates sudo vim unzip awscli nginx supervisor\
  && apt-get autoremove -y\
  && rm -rf /var/lib/apt/lists/* && apt-get clean
RUN pip install -q --upgrade pip
RUN locale-gen en_AU.UTF-8

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY requirements.txt requirements.txt
COPY server.py server.py
RUN pip install -q -r requirements.txt
EXPOSE 8000

CMD ["/usr/bin/supervisord"]
